name: life_simulator
description: A life simulation game

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  # Config files for game data
  assets:
    - assets/config/activities.json
    - assets/config/jobs.json
    - assets/config/store_items.json
    - assets/config/events.json
    - assets/config/game_settings.json
    - assets/config/socialization.json